solution2: solution_v2.c quickSort/quick_sort.c 
	gcc -o solution_v2 solution_v2.c quickSort/quick_sort.c -I quickSort/

solution1: solution.c
	gcc -o solution_v1 solution.c

clear:
	rm solution_v1 solution_v2
